services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: fly
            POSTGRES_USER: siva
            POSTGRES_PASSWORD: siva
        # volumes:
        #     - ./postgres/db_data/:/var/lib/postgresql/data
        #     - ./postgres/db_init/:/docker-entrypoint-initdb.d/
     
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U siva -d fly"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

    pgweb:
        image: sosedoff/pgweb
        ports: 
            - "8081:8081" 
            # - "8082:8082" 
        environment:
            - PGWEB_DATABASE_URL=postgres://siva:siva@db:5432/fly?sslmode=disable
        depends_on:
            db:
                condition: service_healthy
